const mongoose = require('mongoose');

const orderSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  orderItems: [{
    product: { type: mongoose.Schema.Types.ObjectId, ref: 'Product' },
    name: String,
    image: String,
    price: Number,
    quantity: Number,
    size: String,
    color: String,
  }],
  shippingAddress: {
    name: String,
    phone: String,
    email: String,
    house: String,
    street: String,
    landmark: String,
    city: String,
    state: String,
    pincode: String,
    country: { type: String, default: 'India' },
    addressType: { type: String, default: 'Home' },
  },
  paymentMethod: {
    type: String,
    enum: [
      'COD',
      'Razorpay',
      'UPI',
      'Card',
      'Wallet',
      'BankTransfer',
      'PayAfterConfirm',
      'DesignConsultation',
      'Showroom',
    ],
    default: 'COD',
  },
  paymentResult: {
    id: String,
    status: String,
    updateTime: String,
    emailAddress: String,
  },
  deliveryOption: {
    type: String,
    enum: ['standard', 'express'],
    default: 'standard',
  },
  itemsPrice: { type: Number, default: 0 },
  shippingPrice: { type: Number, default: 0 },
  taxPrice: { type: Number, default: 0 },
  discountAmount: { type: Number, default: 0 },
  couponCode: { type: String, default: '' },
  totalPrice: { type: Number, default: 0 },
  isPaid: { type: Boolean, default: false },
  paidAt: Date,
  orderStatus: {
    type: String,
    enum: ['Pending', 'Confirmed', 'Processing', 'Shipped', 'Delivered', 'Cancelled', 'Returned'],
    default: 'Pending',
  },
  trackingNumber: String,
  deliveredAt: Date,
  statusHistory: [{
    status: String,
    message: String,
    timestamp: { type: Date, default: Date.now },
  }],
  notes: String,
}, { timestamps: true });

module.exports = mongoose.model('Order', orderSchema);
